language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.3
sudo: false
addons:
  postgresql: "9.4"
env:
  - MIX_ENV=test
before_script:
  - mix deps.get --only test
  - mix do ecto.create, ecto.migrate
script:
  - mix coveralls.travis
