language: elixir
elixir:
  - 1.4.0
otp_release:
  - 19.2
sudo: false
addons:
  postgresql: "9.6"
before_script:
  - MIX_ENV=test mix compile 
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
script:
  - mix test --trace --cover
