language: elixir
elixir:
  - 1.4.1
otp_release:
  - 19.2
sudo: false
addons:
  postgresql: "9.4"
env:
  - MIX_ENV=test
before_script:
  - mix deps.get --only test
  - mix do ecto.create, ecto.migrate
script:
  - mix coveralls
